/*****************************************************************************
 * Name           : Test_BatchContentChangeNotification
 * Created On     : June 6, 2013
 * Created By     : Parul Gupta(Appirio Offshore)
 * Task Number    : TA1000
 * Implementation : Test class for BatchContentChangeNotification
******************************************************************************/
@isTest
private class Test_BatchContentChangeNotification {

    static testMethod void testBatchContentChangeNotification() {
        // TO DO: implement unit test
    }
}